title: Manasi Blog
author: Manasi
email: manasi.sudhir@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi. This is my blog where I write on my thoughts on technical writing trends and also my expeririences.

# social links

github_username:  https://github.com/ManasiGandhi

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
